server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:payments;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 3000


spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

app:
  api-key: super-secret-123
