package com.tonyyuan.paymentappbackend.dto;

import lombok.Getter;
import lombok.Setter;

/**
 * Response object returned after successfully creating a payment.
 * Contains metadata about the transaction but never exposes sensitive data (e.g., PAN, CVV).
 */
@Getter
@Setter
public class PaymentResponse {

    /** Unique identifier for the payment, generated by the system. */
    private String paymentId;

    /** Current status of the payment (e.g., SUCCEEDED, FAILED, PENDING). */
    private String status;

    /** Amount of the payment in minor units (e.g., cents). */
    private long amountMinor;

    /** Currency code in ISO 4217 format (e.g., USD, AUD). */
    private String currency;

    /** Masked card number (e.g., ************1234). */
    private String maskedCard;

    /** Detected card brand (e.g., Visa, Mastercard, Amex). */
    private String brand;

    /** Expiry month of the card. */
    private int expiryMonth;

    /** Expiry year of the card. */
    private int expiryYear;

    /** The client/tenant ID associated with this payment. */
    private String clientId;

    /** Idempotency key provided in the request, echoed back for reference. */
    private String idempotencyKey;

    // Default constructor (needed by frameworks like Jackson)
    public PaymentResponse() {}

    // Convenience constructor for building responses quickly
    public PaymentResponse(String paymentId, String status, long amountMinor, String currency,
                           String maskedCard, String brand, int expiryMonth, int expiryYear,
                           String clientId, String idempotencyKey) {
        this.paymentId = paymentId;
        this.status = status;
        this.amountMinor = amountMinor;
        this.currency = currency;
        this.maskedCard = maskedCard;
        this.brand = brand;
        this.expiryMonth = expiryMonth;
        this.expiryYear = expiryYear;
        this.clientId = clientId;
        this.idempotencyKey = idempotencyKey;
    }
}
